name: "Terraform Deploy"
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: "Checkout"
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.7  # Use your preferred Terraform version

      # Step 3: Terraform Format Check
      - name: "Terraform Format"
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      # Step 4: Initialize Terraform
      - name: "Terraform Init"
        id: init
        run: terraform init
        working-directory: ./terraform

      # Step 5: Terraform Validate
      - name: "Terraform Validate"
        id: validate
        run: terraform validate -no-color
        working-directory: ./terraform

      # Step 6: Plan the Terraform deployment
      - name: "Terraform Plan"
        id: plan
        run: terraform plan -no-color
        working-directory: ./terraform
        env:
          TF_VAR_agent_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_agent_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      # Step 7: Apply Terraform changes
      - name: "Terraform Apply"
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          TF_VAR_agent_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_agent_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      # Step 8: Output Public IP Address (display the public IP of the VM after deployment)
      - name: "Output Public IP Address"
        run: echo "Public IP Address: $(terraform output -raw public_ip_address)"
        working-directory: ./terraform
